packages:
  # 'packages/*'는 packages 폴더 아래의 모든 폴더를 개별 패키지로 인식하겠다는 의미입니다.
  # 이곳에 UI 컴포넌트, 훅 등이 위치하게 됩니다.
  - "packages/*"
  # 'apps/*'는 apps 폴더 아래의 모든 폴더를 개별 패키지로 인식하겠다는 의미입니다.
  # 이곳에는 Next.js, Vite 등으로 만든 애플리케이션(예: 문서 사이트)이 위치합니다.
  - "apps/*"
  # 'tsconfig' 폴더 또한 하나의 패키지로 인식하도록 추가합니다.
  - "tsconfig"
